version: "3"

volumes:
  productdata:


services:
  mysql:
    image: "mysql:8.0.0"
    container_name: mysql
    volumes:
      - productdata:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=mysecret
      - bind-address=0.0.0.0

  dbinit:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      - INITDB=true
      - DBHOST=mysql
    depends_on:
      - mysql

  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
      - frontend
    environment:
      - DBHOST=mysql
    ports:
      - "5000"
    depends_on:
      - mysql

  loadbalancer:
    image: nginx:alpine
    ports:
      - 4000:4000
    links:
      - mvc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
  # loadbalancer:
  #   image: dockercloud/haproxy
  #   ports:
  #     - 3000:80
  #   links:
  #     - mvc
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  #   networks:
  #     - frontend

networks:
  frontend:
  backend: